-- Create employee_activity_period table to track employment periods per employee
-- This replaces the simple is_active flag with a more flexible activity period model

CREATE TABLE {SCHEMA}.employee_activity_period (
    id          INT  NOT NULL IDENTITY(1,1) PRIMARY KEY,
    employee_id INT  NOT NULL REFERENCES {SCHEMA}.employee(employee_id),
    start_date  DATE NOT NULL,
    end_date    DATE NULL
);

CREATE INDEX idx_emp_period ON {SCHEMA}.employee_activity_period(employee_id, start_date);

-- Migrate existing employee data to activity periods
-- Create one period per employee from the old is_active/start_date columns
INSERT INTO {SCHEMA}.employee_activity_period (employee_id, start_date, end_date)
SELECT employee_id,
       ISNULL(start_date, '2000-01-01'),
       CASE WHEN is_active = 0 THEN CAST(GETDATE() AS DATE) ELSE NULL END
FROM {SCHEMA}.employee;

-- Drop old columns from employee table
-- First, find and drop the DEFAULT constraint on is_active (constraint name is generated by SQL Server)
DECLARE @constraint NVARCHAR(200);
SELECT @constraint = dc.name
FROM sys.default_constraints dc
JOIN sys.columns c ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
JOIN sys.tables t ON c.object_id = t.object_id
JOIN sys.schemas s ON t.schema_id = s.schema_id
WHERE s.name = '{SCHEMA}' AND t.name = 'employee' AND c.name = 'is_active';
IF @constraint IS NOT NULL
    EXEC('ALTER TABLE {SCHEMA}.employee DROP CONSTRAINT ' + @constraint);

-- Drop the old columns
ALTER TABLE {SCHEMA}.employee DROP COLUMN is_active;
ALTER TABLE {SCHEMA}.employee DROP COLUMN start_date;
